"""BuildingModel -> EnergyPlus IDF writer.

World coordinates are used throughout (GlobalGeometryRules ... World), so zone
origins stay at 0,0,0 and surface vertices are written as-is. Every zone gets
default internal loads, infiltration, a dual-setpoint thermostat and an
IdealLoadsAirSystem so heating/cooling demand can be compared across zones
without modelling a real HVAC plant.
"""
from __future__ import annotations

import numpy as np

from .model import (
    BuildingModel, CEILING, FLOOR, GROUND, OUTDOORS, ROOF, SURFACE, Surface,
)

IDEAL_LOADS_SUFFIX = "_Ideal_Loads"

_CONSTRUCTION_FOR_TYPE = {
    ("Wall", OUTDOORS): "BEM_Ext_Wall",
    ("Wall", SURFACE): "BEM_Int_Wall",
    ("Wall", "Adiabatic"): "BEM_Int_Wall",
    ("Floor", GROUND): "BEM_Ground_Floor",
    ("Floor", OUTDOORS): "BEM_Exposed_Floor",
    ("Floor", SURFACE): "BEM_Int_Floor",
    ("Floor", "Adiabatic"): "BEM_Int_Floor",
    ("Ceiling", SURFACE): "BEM_Int_Floor",
    ("Ceiling", "Adiabatic"): "BEM_Int_Floor",
    ("Roof", "Adiabatic"): "BEM_Int_Floor",
    ("Ceiling", OUTDOORS): "BEM_Roof",
    ("Roof", OUTDOORS): "BEM_Roof",
    ("Roof", SURFACE): "BEM_Int_Floor",
}


def _fmt(value: float) -> str:
    return f"{value:.4f}".rstrip("0").rstrip(".")


def _obj(idf: list[str], name: str, *fields, comment: str = "") -> None:
    head = f"{name},"
    if comment:
        head += f"  ! {comment}"
    idf.append(head)
    for i, f in enumerate(fields):
        sep = ";" if i == len(fields) - 1 else ","
        idf.append(f"  {f}{sep}")
    idf.append("")


def _surface_block(idf: list[str], s: Surface) -> None:
    construction = _CONSTRUCTION_FOR_TYPE.get(
        (s.surface_type, s.boundary), "BEM_Ext_Wall"
    )
    sun = "SunExposed" if s.boundary == OUTDOORS and s.surface_type != FLOOR else "NoSun"
    wind = "WindExposed" if s.boundary == OUTDOORS and s.surface_type != FLOOR else "NoWind"
    idf.append("BuildingSurface:Detailed,")
    idf.append(f"  {s.name},")
    idf.append(f"  {s.surface_type},")
    idf.append(f"  {construction},")
    idf.append(f"  {s.zone_name},")
    idf.append("  ,")  # space name (E+ >= 9.6 optional)
    idf.append(f"  {s.boundary},")
    idf.append(f"  {s.boundary_object},")
    idf.append(f"  {sun},")
    idf.append(f"  {wind},")
    idf.append("  autocalculate,")
    idf.append(f"  {len(s.vertices)},")
    for i, v in enumerate(s.vertices):
        sep = ";" if i == len(s.vertices) - 1 else ","
        idf.append(f"  {_fmt(v[0])}, {_fmt(v[1])}, {_fmt(v[2])}{sep}")
    idf.append("")
    for w in s.windows:
        idf.append("FenestrationSurface:Detailed,")
        idf.append(f"  {w.name},")
        idf.append("  Window,")
        idf.append("  BEM_Window,")
        idf.append(f"  {s.name},")
        idf.append("  ,")  # outside boundary condition object
        idf.append("  autocalculate,")  # view factor to ground
        idf.append("  ,")  # frame and divider
        idf.append("  1,")  # multiplier
        idf.append(f"  {len(w.vertices)},")
        for i, v in enumerate(w.vertices):
            sep = ";" if i == len(w.vertices) - 1 else ","
            idf.append(f"  {_fmt(v[0])}, {_fmt(v[1])}, {_fmt(v[2])}{sep}")
        idf.append("")


def generate_idf(model: BuildingModel, cfg: dict) -> str:
    loads = cfg["loads"]
    cons = cfg["constructions"]
    sim = cfg["simulation"]
    site = cfg.get("site", {})
    hvac = cfg.get("hvac", {})
    schedules = cfg.get("schedules", {})
    rp = sim.get("run_period", [1, 1, 12, 31])
    idf: list[str] = []

    idf.append(f"! Generated by bim_to_bem pipeline from {model.source_file}")
    for note in model.notes:
        idf.append(f"! note: {note}")
    idf.append("")

    _obj(idf, "Version", cfg.get("idf_version", "25.2"))
    _obj(idf, "SimulationControl", "No", "No", "No", "No", "Yes")
    _obj(idf, "Timestep", sim.get("timestep", 4))
    _obj(idf, "RunPeriod", "Annual_Run", rp[0], rp[1], "", rp[2], rp[3], "",
         "Tuesday", "Yes", "Yes", "No", "Yes", "Yes")
    _obj(idf, "Building", model.name, _fmt(model.north_axis_deg),
         site.get("terrain", "Suburbs"), 0.04, 0.4, "FullExterior", 25, 6)
    _obj(idf, "GlobalGeometryRules", "UpperLeftCorner", "CounterClockWise", "World")
    ground_temps = (site.get("ground_temps_c") or [18.0] * 12)[:12]
    ground_temps += [18.0] * (12 - len(ground_temps))
    _obj(idf, "Site:GroundTemperature:BuildingSurface", *ground_temps)

    # --- materials & constructions -----------------------------------------
    # Opaque assemblies are modelled as one massive layer plus a no-mass
    # insulation layer sized so the assembly hits the configured U-value.
    def r_extra(u_target: float, base_r: float) -> float:
        return max(0.001, 1.0 / max(0.05, u_target) - base_r - 0.17)  # films ~0.17

    _obj(idf, "Material", "BEM_Concrete_200", "MediumRough", 0.2, 1.63, 2300,
         1000, 0.9, 0.7, 0.7)
    _obj(idf, "Material", "BEM_Concrete_150", "MediumRough", 0.15, 1.63, 2300,
         1000, 0.9, 0.7, 0.7)
    _obj(idf, "Material", "BEM_Gypsum_25", "Smooth", 0.025, 0.16, 800, 1090,
         0.9, 0.5, 0.5)
    _obj(idf, "Material:NoMass", "BEM_Ins_Wall", "Rough",
         _fmt(r_extra(cons["ext_wall_u"], 0.2 / 1.63)), 0.9, 0.7, 0.7)
    _obj(idf, "Material:NoMass", "BEM_Ins_Roof", "Rough",
         _fmt(r_extra(cons["roof_u"], 0.15 / 1.63)), 0.9, 0.7, 0.7)
    _obj(idf, "WindowMaterial:SimpleGlazingSystem", "BEM_Glazing",
         _fmt(cons["window_u"]), _fmt(cons["window_shgc"]), 0.7)

    _obj(idf, "Construction", "BEM_Ext_Wall", "BEM_Ins_Wall", "BEM_Concrete_200")
    _obj(idf, "Construction", "BEM_Int_Wall", "BEM_Gypsum_25")
    _obj(idf, "Construction", "BEM_Ground_Floor", "BEM_Concrete_200")
    _obj(idf, "Construction", "BEM_Exposed_Floor", "BEM_Ins_Roof", "BEM_Concrete_200")
    _obj(idf, "Construction", "BEM_Int_Floor", "BEM_Concrete_150")
    _obj(idf, "Construction", "BEM_Roof", "BEM_Ins_Roof", "BEM_Concrete_150")
    _obj(idf, "Construction", "BEM_Window", "BEM_Glazing")

    # --- schedules -----------------------------------------------------------
    _obj(idf, "ScheduleTypeLimits", "BEM_Fraction", 0.0, 1.0, "Continuous")
    _obj(idf, "ScheduleTypeLimits", "BEM_Temperature", -60, 200, "Continuous")
    _obj(idf, "ScheduleTypeLimits", "BEM_ControlType", 0, 4, "Discrete")
    _obj(idf, "ScheduleTypeLimits", "BEM_AnyNumber", "", "", "Continuous")
    _obj(idf, "Schedule:Constant", "BEM_Always_On", "BEM_Fraction", 1.0)
    # occupancy-driven internal loads: profile from config (schedules section)
    occ_steps = schedules.get("occupancy_weekday") or [[7, 0.1], [19, 1.0], [24, 0.2]]
    occ_fields: list = ["Through: 12/31", "For: Weekdays"]
    for until_hour, frac in occ_steps:
        occ_fields += [f"Until: {int(until_hour):02d}:00", frac]
    occ_fields += ["For: AllOtherDays", "Until: 24:00",
                   schedules.get("occupancy_other_days", 0.3)]
    _obj(idf, "Schedule:Compact", "BEM_Occupancy", "BEM_Fraction", *occ_fields)
    _obj(idf, "Schedule:Constant", "BEM_Ctrl_DualSetpoint", "BEM_ControlType", 4)
    _obj(idf, "Schedule:Constant", "BEM_Heat_Setpoint", "BEM_Temperature",
         _fmt(loads["heating_setpoint_c"]))
    _obj(idf, "Schedule:Constant", "BEM_Cool_Setpoint", "BEM_Temperature",
         _fmt(loads["cooling_setpoint_c"]))
    _obj(idf, "Schedule:Constant", "BEM_Activity", "BEM_AnyNumber",
         _fmt(loads["activity_level_w"]))

    # --- zones, surfaces, loads, HVAC ---------------------------------------
    for z in model.zones:
        _obj(idf, "Zone", z.name, 0, 0, 0, 0, 1, 1, "autocalculate",
             _fmt(max(1.0, z.volume)), _fmt(max(0.5, z.floor_area)))

    for z in model.zones:
        for s in z.surfaces:
            _surface_block(idf, s)

    for z in model.zones:
        _obj(idf, "People", f"{z.name}_People", z.name, "BEM_Occupancy",
             "People/Area", "", _fmt(loads["people_per_area"]), "", 0.3, "",
             "BEM_Activity")
        _obj(idf, "Lights", f"{z.name}_Lights", z.name, "BEM_Occupancy",
             "Watts/Area", "", _fmt(loads["lights_w_per_area"]), "", 0.2, 0.4,
             0.2, 1.0)
        _obj(idf, "ElectricEquipment", f"{z.name}_Equip", z.name,
             "BEM_Occupancy", "Watts/Area", "", _fmt(loads["equipment_w_per_area"]),
             "", 0.1, 0.3, 0.0)
        _obj(idf, "ZoneInfiltration:DesignFlowRate", f"{z.name}_Infiltration",
             z.name, "BEM_Always_On", "AirChanges/Hour", "", "", "",
             _fmt(loads["infiltration_ach"]), 1, 0, 0, 0)
        _obj(idf, "ZoneControl:Thermostat", f"{z.name}_Thermostat", z.name,
             "BEM_Ctrl_DualSetpoint", "ThermostatSetpoint:DualSetpoint",
             f"{z.name}_DualSetpoint")
        _obj(idf, "ThermostatSetpoint:DualSetpoint", f"{z.name}_DualSetpoint",
             "BEM_Heat_Setpoint", "BEM_Cool_Setpoint")
        _obj(idf, "ZoneHVAC:EquipmentConnections", z.name,
             f"{z.name}_Equipment", f"{z.name}_Inlets", "",
             f"{z.name}_Air_Node", f"{z.name}_Return_Node")
        _obj(idf, "NodeList", f"{z.name}_Inlets", f"{z.name}_Supply_Inlet")
        _obj(idf, "ZoneHVAC:EquipmentList", f"{z.name}_Equipment",
             "SequentialLoad", "ZoneHVAC:IdealLoadsAirSystem",
             f"{z.name}{IDEAL_LOADS_SUFFIX}", 1, 1)
        # ASHRAE 62.1 outdoor air (L/s -> m3/s), served by the ideal loads system
        _obj(idf, "DesignSpecification:OutdoorAir", f"{z.name}_OA", "Sum",
             _fmt(loads.get("ventilation_l_s_person", 0.0) / 1000.0),
             _fmt(loads.get("ventilation_l_s_m2", 0.0) / 1000.0), 0, 0)
        _obj(idf, "ZoneHVAC:IdealLoadsAirSystem", f"{z.name}{IDEAL_LOADS_SUFFIX}",
             "", f"{z.name}_Supply_Inlet", "", "",
             _fmt(hvac.get("max_heating_supply_air_temp_c", 50.0)),
             _fmt(hvac.get("min_cooling_supply_air_temp_c", 13.0)),
             _fmt(hvac.get("max_heating_supply_humidity_ratio", 0.0156)),
             _fmt(hvac.get("min_cooling_supply_humidity_ratio", 0.0077)),
             "NoLimit", "", "", "NoLimit", "", "",
             "", "", "", "", "", f"{z.name}_OA")

    # --- outputs -------------------------------------------------------------
    _obj(idf, "Output:Variable", "*",
         "Zone Ideal Loads Supply Air Total Heating Energy", "Monthly")
    _obj(idf, "Output:Variable", "*",
         "Zone Ideal Loads Supply Air Total Cooling Energy", "Monthly")
    _obj(idf, "Output:Variable", "*", "Zone Mean Air Temperature", "Monthly")
    _obj(idf, "Output:Variable", "*", "Zone Operative Temperature", "Monthly")
    _obj(idf, "Output:Variable", "*", "Zone Air Relative Humidity", "Monthly")
    _obj(idf, "Output:Variable", "*",
         "Enclosure Windows Total Transmitted Solar Radiation Energy", "Monthly")
    # per-surface shadow analysis (aggregated to zones by the results parser)
    _obj(idf, "Output:Variable", "*", "Surface Outside Face Sunlit Fraction", "Monthly")
    _obj(idf, "OutputControl:Table:Style", "HTML", "JtoKWH")
    _obj(idf, "Output:Table:SummaryReports", "AllSummary")

    return "\n".join(idf)


def write_idf(model: BuildingModel, cfg: dict, out_path: str) -> str:
    text = generate_idf(model, cfg)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)
    return out_path
